language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
    - name: "Python 3.8.0 on FreeBSD"
      os: freebsd
      python: 3.8
    - name: "Python 3.8.0 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      python: 3.8
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      python: 3.8

# command to install dependencies
install:
  - pip install -r requirements/development.txt
# command to run tests
script:
  - pytest