# 参考
# Build and push Docker images
# https://github.com/marketplace/actions/build-and-push-docker-images
# Docker Metadata action
# https://github.com/marketplace/actions/docker-metadata-action
# Multi-platform image with GitHub Actions
# https://docs.docker.com/build/ci/github-actions/multi-platform/

name: Docker Publish

#on:
#  release:
#    types: [published]
#  push:
#    branch: ['master']
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
            images: mouday/domain-admin

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'mouday'
          repository: 'domain-admin-web'
          access-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Move Web Dist code
        run: |
          mv domain-admin-web domain_admin/public

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
