name: Auto Build Docker Image
run-name: auto-builder
on: [ push ]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: benjlevesque/short-sha@v2.0
        id: short-sha
        with:
          length: 6
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/domain-admin:${{ steps.short-sha.outputs.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/domain-admin:latest
          cache-from: type=registry,ref=${{ github.repository }}:latest
          cache-to: type=inline