#https://github.com/yyx990803/release-tag

name: Create Release

#on:
#  push:
#    tags:
#      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

on:
  push:
    branch: ['master']

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'mouday'
          repository: 'domain-admin-web'
          access-token: ${{ secrets.ACCESS_TOKEN }}

#      - name: Move Web Dist code
#        run: |
#          mv domain-admin-web domain_admin/public

      - name: Create Release for Tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/mouday/domain-admin/blob/master/CHANGELOG.md) for details.